### ISSUE TITLE
Enhancement/for the future: add-on to conditionally colour the output metricsTSV and save as an Excel doc

### ISSUE THREAD

**Issue by corbin-chris** [eastgenomics/eggd_tso500#8]
The CSV of output metrics gets manually checked, with threshold failures highlighted for information. This adds a few minutes to the checking process. It might be nice to incorporate a small post-processing step which uses Python xlsxwriter (https://xlsxwriter.readthedocs.io/working_with_conditional_formats.html) to:
- Make an xlsx copy of the metrics output
- Carry out conditional colouring automatically

**Comment by jethror1** [comment]
closing as being completed in: https://github.com/eastgenomics/eggd_MetricsOutput_edit
