### ISSUE TITLE
Illumina link from README.md does not work

### ISSUE THREAD

**Issue by Arun-bioinformatics** [eastgenomics/eggd_tso500#9]
Hello, I am aware that the link (https://emea.support.illumina.com/downloads/trusight-oncology-500-local-app-user-guide-1000000067616.html) should be a pdf document. Would it be possible to update this to include a new working link or could the pdf be included in the repo? Thanks!

**Comment by Arun-bioinformatics** [comment]
I just realised that the same issue was pointed out by @woook last year.

**Comment by jethror1** [comment]
Fixed in #12
